### ISSUE TITLE
add new action: community-code for update community member

### ISSUE THREAD

**Issue by manh-vv** [canfoundation/cif-js#41]
There will be a new community code added to GOD. And we have to update the [cif-j](https://github.com/canfoundation/cif-js)s as well.

/cc @phanduy12214  @ntpdung  please handle the issue. For more information, please contact @danielAlvess 

https://git.baikal.io/can/cif-be/issues/21#note_138857

**Comment by manh-vv** [comment]
btw, could @danielAlvess change the name into which contains Quy? It quite takes my time to search your name 😅

**Comment by danielAlvess** [comment]
This feature has been implemented in PR https://github.com/canfoundation/cif-js/pull/44
