### ISSUE TITLE
[Bug Safari] Safari does not support BigInt 

### ISSUE THREAD

**Issue by ntpdung** [canfoundation/cif-js#54]

**Comment by ntpdung** [comment]
i have a solution that using a big-integer library.
https://www.npmjs.com/package/big-integer

@danielAlvess do you have any idea?

**Comment by danielAlvess** [comment]
> i have a solution that using a big-integer library.
It LGTM

**Comment by ntpdung** [comment]
@diemnguyen2104 do you excited to do it?
